function root = init_paths()
% INIT_PATHS  Put the project on the MATLAB path. Called by every entry
%   point; safe to call repeatedly.
    root = fileparts(mfilename('fullpath'));
    addpath(root, ...
            fullfile(root, 'config'), ...
            genpath(fullfile(root, 'src')), ...
            fullfile(root, 'validation'), ...
            fullfile(root, 'tests'), ...
            fullfile(root, 'web_visualizer'));
end
